/**
 * 分类图片图标（`img:` 集）· 由 `scripts/gen-cat-icons.mjs` 生成，**请勿手改**。
 *
 * 重新生成：`node scripts/gen-cat-icons.mjs`
 *
 * 与其它图标集的分工（三套并存，别混用）：
 *   · `icons.ts`       —— 单色界面/分类图标（`icon-*` / `cat-*`），内联 path、跟随 currentColor
 *   · `color-icons.ts` —— 彩色图标（`colorful:` / `life:`），内联 SVG body、动态分包
 *   · 本文件           —— 分类图片图标（`img:<分类名>`），静态 PNG + WebP、按需 HTTP 加载
 *
 * ⚠️ 文件名是**拼音**不是中文名 —— uni-app H5 dev server 的静态中间件不解码 URL，
 *    中文名文件在开发环境 404（详见 gen 脚本头部）。key 仍是中文的分类名。
 *
 * ⚠️ 每个图标有**两份等价产物**：`<基名>.png`（小程序 / App）与 `<基名>.webp`（H5，省 ~88% 体积）。
 *    正文**不带扩展名**，由 `utils/catIcon.ts` 按平台拼（`#ifdef H5` → .webp，否则 .png）——
 *    因为"哪端能用 WebP"是平台知识，属于取数逻辑，不该固化进生成物。
 *    为什么不能统一用 WebP：无法离线确认微信小程序对"包内本地 webp"的支持，
 *    一旦不支持就是 `<image>` 安静地显示空白。详见 gen 脚本头部"为什么要生成两份"。
 *
 * ⚠️ 本集**不进 JS bundle**：两套图都放在 `static/cat-icons/`，
 *    由 `<image src="/static/cat-icons/<拼音>.<扩展名>">` 按需加载。
 *    原始 2048px 源图（39MB）备份在 `assets/cat-icons-original/`，不参与构建。
 */

/** 全部图片图标的名字（= 分类名）。key 形态为 `img:<名字>` */
export const CAT_ICON_NAMES: string[] = [
  "按揭还款",
  "保健费",
  "保健品",
  "保险报销",
  "柴米油盐蔬菜瓜果",
  "宠物宝贝",
  "慈善捐助",
  "打车租车",
  "电脑",
  "电影娱乐",
  "房租",
  "房租收入",
  "工资收入",
  "公共交通",
  "公积金提款",
  "共享带宽收入",
  "还人钱物",
  "红包",
  "护肤品",
  "花草类",
  "化妆饰品",
  "会员订阅",
  "火锅",
  "加班收入",
  "家具",
  "家用电器",
  "兼职收入",
  "健身卡",
  "奖金收入",
  "教育学费",
  "经营所得",
  "咖啡茶饮",
  "烂账损失",
  "礼金收入",
  "理发",
  "利息收入",
  "利息支出",
  "旅游度假",
  "美甲",
  "美容费",
  "奶茶",
  "培训进修",
  "赔偿罚款",
  "配件",
  "朋友聚会",
  "其他",
  "其他饰品",
  "其他支出",
  "汽车加油",
  "日常用品",
  "上网费",
  "烧烤",
  "食材采购",
  "手机",
  "手机费",
  "书报杂志",
  "数码产品",
  "数码装备",
  "水电煤气宽带",
  "水果零食",
  "顺风车",
  "私家车费用",
  "送礼请客",
  "甜品",
  "投资亏损",
  "投资收入",
  "外卖",
  "晚餐",
  "维修保养",
  "午餐",
  "物品回收",
  "物业管理",
  "消费税收",
  "孝敬家长",
  "鞋帽包包",
  "信用卡还款",
  "休闲玩乐",
  "烟酒茶",
  "药品费",
  "夜宵",
  "衣服裤子",
  "意外丢失",
  "意外来钱",
  "银行手续",
  "邮寄费",
  "游泳",
  "瑜伽",
  "运动健身",
  "早餐",
  "早午晚餐",
  "治疗费",
  "中奖收入",
  "座机费",
  "AA还款",
];

/**
 * 名字 → **基名**：`static/cat-icons/` 下的文件名**去掉扩展名**（`"wucan"`，不是 `"wucan.png"`）。
 *
 * ⚠️ 为什么不带扩展名：同名的两份产物（`.png` 给小程序/App、`.webp` 给 H5）都合法，
 *    扩展名取决于**消费端的平台**，不是图标本身的属性 —— 让消费方拼，这里只存公共前缀。
 *    具体拼法见 `utils/catIcon.ts` 的 `catIconSrc()`。
 */
export const CAT_ICON_FILES: Record<string, string> = {
  "按揭还款": "anjiehaikuan",
  "保健费": "baojianfei",
  "保健品": "baojianpin",
  "保险报销": "baoxianbaoxiao",
  "柴米油盐蔬菜瓜果": "chaimiyouyanshucaiguaguo",
  "宠物宝贝": "chongwubaobei",
  "慈善捐助": "cishanjuanzhu",
  "打车租车": "dachezuche",
  "电脑": "diannao",
  "电影娱乐": "dianyingyule",
  "房租": "fangzu",
  "房租收入": "fangzushouru",
  "工资收入": "gongzishouru",
  "公共交通": "gonggongjiaotong",
  "公积金提款": "gongjijintikuan",
  "共享带宽收入": "gongxiangdaikuanshouru",
  "还人钱物": "hairenqianwu",
  "红包": "hongbao",
  "护肤品": "hufupin",
  "花草类": "huacaolei",
  "化妆饰品": "huazhuangshipin",
  "会员订阅": "huiyuandingyue",
  "火锅": "huoguo",
  "加班收入": "jiabanshouru",
  "家具": "jiaju",
  "家用电器": "jiayongdianqi",
  "兼职收入": "jianzhishouru",
  "健身卡": "jianshenka",
  "奖金收入": "jiangjinshouru",
  "教育学费": "jiaoyuxuefei",
  "经营所得": "jingyingsuode",
  "咖啡茶饮": "kafeichayin",
  "烂账损失": "lanzhangsunshi",
  "礼金收入": "lijinshouru",
  "理发": "lifa",
  "利息收入": "lixishouru",
  "利息支出": "lixizhichu",
  "旅游度假": "lvyoudujia",
  "美甲": "meijia",
  "美容费": "meirongfei",
  "奶茶": "naicha",
  "培训进修": "peixunjinxiu",
  "赔偿罚款": "peichangfakuan",
  "配件": "peijian",
  "朋友聚会": "pengyoujuhui",
  "其他": "qita",
  "其他饰品": "qitashipin",
  "其他支出": "qitazhichu",
  "汽车加油": "qichejiayou",
  "日常用品": "richangyongpin",
  "上网费": "shangwangfei",
  "烧烤": "shaokao",
  "食材采购": "shicaicaigou",
  "手机": "shouji",
  "手机费": "shoujifei",
  "书报杂志": "shubaozazhi",
  "数码产品": "shumachanpin",
  "数码装备": "shumazhuangbei",
  "水电煤气宽带": "shuidianmeiqikuandai",
  "水果零食": "shuiguolingshi",
  "顺风车": "shunfengche",
  "私家车费用": "sijiachefeiyong",
  "送礼请客": "songliqingke",
  "甜品": "tianpin",
  "投资亏损": "touzikuisun",
  "投资收入": "touzishouru",
  "外卖": "waimai",
  "晚餐": "wancan",
  "维修保养": "weixiubaoyang",
  "午餐": "wucan",
  "物品回收": "wupinhuishou",
  "物业管理": "wuyeguanli",
  "消费税收": "xiaofeishuishou",
  "孝敬家长": "xiaojingjiazhang",
  "鞋帽包包": "xiemaobaobao",
  "信用卡还款": "xinyongkahaikuan",
  "休闲玩乐": "xiuxianwanle",
  "烟酒茶": "yanjiucha",
  "药品费": "yaopinfei",
  "夜宵": "yexiao",
  "衣服裤子": "yifukuzi",
  "意外丢失": "yiwaidiushi",
  "意外来钱": "yiwailaiqian",
  "银行手续": "yinhangshouxu",
  "邮寄费": "youjifei",
  "游泳": "youyong",
  "瑜伽": "yujia",
  "运动健身": "yundongjianshen",
  "早餐": "zaocan",
  "早午晚餐": "zaowuwancan",
  "治疗费": "zhiliaofei",
  "中奖收入": "zhongjiangshouru",
  "座机费": "zuojifei",
  "AA还款": "aahaikuan",
};

/** 图标总数（图标选择器 Tab 上显示，也用于自检） */
export const CAT_ICON_TOTAL = 94;
