/**
 * 分类图片图标（`img:` 集）· 由 `scripts/gen-cat-icons.mjs` 生成，**请勿手改**。
 *
 * 重新生成：`node scripts/gen-cat-icons.mjs`
 *
 * 与其它图标集的分工（三套并存，别混用）：
 *   · `icons.ts`       —— 单色界面/分类图标（`icon-*` / `cat-*`），内联 path、跟随 currentColor
 *   · `color-icons.ts` —— 彩色图标（`colorful:` / `life:`），内联 SVG body、动态分包
 *   · 本文件           —— 分类图片图标（`img:<分类名>`），静态 PNG、按需 HTTP 加载
 *
 * ⚠️ 文件名是**拼音**不是中文名 —— uni-app H5 dev server 的静态中间件不解码 URL，
 *    中文名文件在开发环境 404（详见 gen 脚本头部）。key 仍是中文的分类名。
 *
 * ⚠️ 本集**不进 JS bundle**：PNG 放在 `static/cat-icons/`，
 *    由 `<image src="/static/cat-icons/<拼音>.png">` 按需加载。
 *    原始 2048px 源图（39MB）备份在 `assets/cat-icons-original/`，不参与构建。
 */

/** 全部图片图标的名字（= 分类名）。key 形态为 `img:<名字>` */
export const CAT_ICON_NAMES: string[] = [
  "按揭还款",
  "保健费",
  "保健品",
  "柴米油盐蔬菜瓜果",
  "宠物宝贝",
  "慈善捐助",
  "打车租车",
  "电脑",
  "电影娱乐",
  "房租",
  "公共交通",
  "还人钱物",
  "红包",
  "护肤品",
  "花草类",
  "化妆饰品",
  "会员订阅",
  "火锅",
  "家具",
  "家用电器",
  "健身卡",
  "教育学费",
  "咖啡茶饮",
  "烂账损失",
  "理发",
  "利息支出",
  "旅游度假",
  "美甲",
  "美容费",
  "奶茶",
  "培训进修",
  "赔偿罚款",
  "配件",
  "朋友聚会",
  "其他饰品",
  "其他支出",
  "汽车加油",
  "日常用品",
  "上网费",
  "烧烤",
  "食材采购",
  "手机",
  "手机费",
  "书报杂志",
  "数码产品",
  "数码装备",
  "水电煤气宽带",
  "水果零食",
  "私家车费用",
  "送礼请客",
  "甜品",
  "投资亏损",
  "外卖",
  "晚餐",
  "维修保养",
  "午餐",
  "物业管理",
  "消费税收",
  "孝敬家长",
  "鞋帽包包",
  "休闲玩乐",
  "烟酒茶",
  "药品费",
  "夜宵",
  "衣服裤子",
  "意外丢失",
  "银行手续",
  "邮寄费",
  "游泳",
  "瑜伽",
  "运动健身",
  "早餐",
  "早午晚餐",
  "治疗费",
  "座机费",
];

/** 名字 → 文件名（`static/cat-icons/` 下的 PNG，文件名为拼音） */
export const CAT_ICON_FILES: Record<string, string> = {
  "按揭还款": "anjiehaikuan.png",
  "保健费": "baojianfei.png",
  "保健品": "baojianpin.png",
  "柴米油盐蔬菜瓜果": "chaimiyouyanshucaiguaguo.png",
  "宠物宝贝": "chongwubaobei.png",
  "慈善捐助": "cishanjuanzhu.png",
  "打车租车": "dachezuche.png",
  "电脑": "diannao.png",
  "电影娱乐": "dianyingyule.png",
  "房租": "fangzu.png",
  "公共交通": "gonggongjiaotong.png",
  "还人钱物": "hairenqianwu.png",
  "红包": "hongbao.png",
  "护肤品": "hufupin.png",
  "花草类": "huacaolei.png",
  "化妆饰品": "huazhuangshipin.png",
  "会员订阅": "huiyuandingyue.png",
  "火锅": "huoguo.png",
  "家具": "jiaju.png",
  "家用电器": "jiayongdianqi.png",
  "健身卡": "jianshenka.png",
  "教育学费": "jiaoyuxuefei.png",
  "咖啡茶饮": "kafeichayin.png",
  "烂账损失": "lanzhangsunshi.png",
  "理发": "lifa.png",
  "利息支出": "lixizhichu.png",
  "旅游度假": "lvyoudujia.png",
  "美甲": "meijia.png",
  "美容费": "meirongfei.png",
  "奶茶": "naicha.png",
  "培训进修": "peixunjinxiu.png",
  "赔偿罚款": "peichangfakuan.png",
  "配件": "peijian.png",
  "朋友聚会": "pengyoujuhui.png",
  "其他饰品": "qitashipin.png",
  "其他支出": "qitazhichu.png",
  "汽车加油": "qichejiayou.png",
  "日常用品": "richangyongpin.png",
  "上网费": "shangwangfei.png",
  "烧烤": "shaokao.png",
  "食材采购": "shicaicaigou.png",
  "手机": "shouji.png",
  "手机费": "shoujifei.png",
  "书报杂志": "shubaozazhi.png",
  "数码产品": "shumachanpin.png",
  "数码装备": "shumazhuangbei.png",
  "水电煤气宽带": "shuidianmeiqikuandai.png",
  "水果零食": "shuiguolingshi.png",
  "私家车费用": "sijiachefeiyong.png",
  "送礼请客": "songliqingke.png",
  "甜品": "tianpin.png",
  "投资亏损": "touzikuisun.png",
  "外卖": "waimai.png",
  "晚餐": "wancan.png",
  "维修保养": "weixiubaoyang.png",
  "午餐": "wucan.png",
  "物业管理": "wuyeguanli.png",
  "消费税收": "xiaofeishuishou.png",
  "孝敬家长": "xiaojingjiazhang.png",
  "鞋帽包包": "xiemaobaobao.png",
  "休闲玩乐": "xiuxianwanle.png",
  "烟酒茶": "yanjiucha.png",
  "药品费": "yaopinfei.png",
  "夜宵": "yexiao.png",
  "衣服裤子": "yifukuzi.png",
  "意外丢失": "yiwaidiushi.png",
  "银行手续": "yinhangshouxu.png",
  "邮寄费": "youjifei.png",
  "游泳": "youyong.png",
  "瑜伽": "yujia.png",
  "运动健身": "yundongjianshen.png",
  "早餐": "zaocan.png",
  "早午晚餐": "zaowuwancan.png",
  "治疗费": "zhiliaofei.png",
  "座机费": "zuojifei.png",
};

/** 图标总数（图标选择器 Tab 上显示，也用于自检） */
export const CAT_ICON_TOTAL = 75;
